<?php 



/**
 * implementation in flag module
 */
function flag_application_flag_flag($flag, $entity_id, $account, $flagging) {
	
	if( $flag->name == 'bookmarks') {
		$insert = db_insert('flag_application')
				  ->fields(
					array(
					'flagging_id' => $flagging->flagging_id,
					'entity_id'   => $entity_id,
					'status'	  => 1,
					'app_name' => $flag->name
					)
				)
				->execute();
	}
}

/**
 * Implement Hook_flag_default_flag.
 */
function flag_application_flag_default_flags() {
	$flags = array();
	// Exported flag: "Bookmarks".
	$flags['bookmarks'] = array (
	  'entity_type' => 'node',
	  'title' => 'Bookmarks',
	  'global' => '1',
	  'types' => 
	  array (
	    0 => 'book',
	  ),
	  'flag_short' => 'Buy Book',
	  'flag_long' => 'Add this post to your bookmarks',
	  'flag_message' => 'This post has been added to your bookmarks',
	  'unflag_short' => 'Download PDF',
	  'unflag_long' => 'Remove this post from your bookmarks',
	  'unflag_message' => 'This post has been removed from your bookmarks',
	  'unflag_denied_text' => '',
	  'link_type' => 'toggle',
	  'weight' => 0,
	  'show_in_links' => 
	  array (
	    'full' => 'full',
	    'teaser' => 'teaser',
	    'rss' => 0,
	    'search_index' => 0,
	    'search_result' => 0,
	    'print' => 0,
	  ),
	  'show_as_field' => 0,
	  'show_on_form' => 1,
	  'access_author' => '',
	  'show_contextual_link' => 0,
	  'i18n' => 0,
	  'api_version' => 3,
	);
return $flags;
}

?>