<?php 


function download_pdf_node_view_alter (){

}

function download_pdf_node_view($node, $view_mode, $langcode) {
  dpm('test');
  switch ($node->type) {     // Node typs is book is our case
    case 'book':
      $node->content['extra_link'] = array(
          '#weight' => 10,
          '#theme' => 'link',
          '#path' => 'path_to_content',
          '#text' => t('Download PDF'),
          '#options' => array(
              'attributes' => array(),
              'html' => FALSE
          ),
      );
      break;
  }
}
?>