<?php 



function download_pdf_node_view_alter (){

}

function download_pdf_node_view($node, $view_mode, $langcode) {

	// Check if the flag is on. 
	$select_query = db_select('flag_application', 'c')
					    ->fields('c')
					    ->condition('entity_id', $node->book['nid'])
					    ->execute()
					    ->fetchAssoc();
	print_r($select_query);
  	if(!empty($node->field_book_pdf_) && !empty($select_query)){
  		$pdf_std = $node->field_book_pdf_;
  		$path = $pdf_std['und'][0]['uri'];
		
		$url = file_create_url($path);
		$url = parse_url($url);
		$file_path = "//{$_SERVER['HTTP_HOST']}".$url['path'];
		//print_r($url);exit;
  	  switch ($node->type) {     // Node typs is book is our case
	    case 'book':
	      $node->content['extra_link'] = array(
	          '#weight' => 10,
	          '#theme' => 'link',
	          '#path' => $file_path	,
	          '#text' => t('Download PDF'),
	          '#options' => array(
	              'attributes' => array(),
	              'html' => FALSE
	          ),
	      );
	      break;
	  }	
  } else {
  	switch ($node->type) {     // Node typs is book is our case
	    case 'book':
	      $node->content['extra_link'] = array();
	      break;
	  }	
  } 
  
}
?>