<?php 

function download_pdf_flag_flag($flag, $entity_id, $account, $flagging) {

	if( $flag->name == 'bookmarks') {
		$insert = db_insert('flag_application')
				  ->fields(
					array(
					'flagging_id' => $flagging->flagging_id,
					'entity_id'   => $entity_id,
					'status'	  => 1,
					'app_name' => $flag->name
					)
				)
				->execute();

	}
}

/**
* implementation of unflag 
*/
function download_pdf_flag_unflag($flag, $entity_id, $account, $flagging) {
	if( $flag->name == 'bookmarks') {
		$insert = db_delete('flag_application')
				  ->condition( 'flagging_id' , $flagging->flagging_id ) 
				  ->condition( 'entity_id' , $entity_id )
				->execute();
	}
}

/**
* Function created to add the link in the node
*/
function download_pdf_node_view($node, $view_mode, $langcode) {

	// Check if the flag is on. 
	$select_query = db_select('flag_application', 'c')
					    ->fields('c')
					    ->condition('entity_id', $node->book['nid'])
					    ->execute()
					    ->fetchAssoc();
	if(!empty($node->field_book_pdf_) && !empty($select_query)){
  		$pdf_std = $node->field_book_pdf_;
  		$path = $pdf_std['und'][0]['uri'];
		
		$url = file_create_url($path);
		$url = parse_url($url);
		$file_path = "//{$_SERVER['HTTP_HOST']}".$url['path'];
		//print_r($url);exit;
  	  switch ($node->type) {     // Node typs is book is our case
	    case 'book':
	      $node->content['extra_link'] = array(
	          '#weight' => 10,
	          '#theme' => 'link',
	          '#path' => $file_path	,
	          '#text' => t('Download PDF'),
	          '#options' => array(
	              'attributes' => array(),
	              'html' => FALSE
	          ),
	      );
	      break;
	  }	
  } 
  
}
?>